services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network


  app:
    build: .
    container_name: app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

    volumes:
      - ./:/usr/src/app/  # Локальные изменения будут отражаться в контейнере
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    #command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always   
    networks:
      - app-network  

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network


  celery:
    build: .  
    container_name: celery
    env_file: .env
    depends_on:
      - app
      - redis
    command: celery -A celery_app worker --loglevel=info  
    restart: always
    networks:
      - app-network



volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  app-network:
    driver: bridge



