# Generated by Django 4.2.16 on 2024-12-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Название населенного пункта')),
                ('latitude', models.FloatField(help_text='Пример: 55.7558', verbose_name='Широта')),
                ('longitude', models.FloatField(help_text='Пример: 37.6176', verbose_name='Долгота')),
                ('house_active', models.BooleanField(default=False, help_text='По дефолту не активно', verbose_name='Подключение домов')),
                ('apartment_active', models.BooleanField(default=False, help_text='По дефолту не активно', verbose_name='Подключение квартир')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('year_tv', 'Год в подарок + ТВ'), ('drugo', 'Друговорот'), ('volokno', 'Волокно за полцены'), ('dvoem', 'Вдвоем за полцены'), ('radio', 'Радио на волокно'), ('stroy', 'Стройплощадка'), ('socpod_tv', 'Соцподдержка + ТВ'), ('vtroem', 'Втроем дешевле'), ('volokno_tv', 'Волокноль ТВ'), ('wifi', 'WIFI у дачи')], max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('discount', models.DecimalField(decimal_places=2, help_text='Сумма скидки', max_digits=6, verbose_name='Скидка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Акция активна')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='UrgentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgent_connection', models.BooleanField(default=False, help_text='Отметьте, если требуется срочное подключение.', verbose_name='Срочное подключение')),
                ('urgent_connection_fee', models.DecimalField(decimal_places=2, default=3500, help_text='Стоимость срочного подключения.', max_digits=10, verbose_name='Стоимость срочного подключения')),
            ],
            options={
                'verbose_name': "Стоимость услуги 'Срочное подключение'",
                'verbose_name_plural': "Стоимость услуги 'Срочное подключение'",
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание оборудования')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('type', models.CharField(blank=True, choices=[('rental', 'Арендованный'), ('budget', 'Бюджетный'), ('two_range', 'Двухдиапазонный'), ('high_speed', 'Высокоскоростной'), ('far_range', 'Дальнобойный')], max_length=45, null=True, verbose_name='Тип')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('is_active', models.BooleanField(default=False, help_text='По дефолту не активно', verbose_name='Активно')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='ConnectionTypePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('house', 'Подключение дома'), ('apartment', 'Подключение квартиры')], default='house', max_length=255, verbose_name='Тип подключения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_types', to='services.locality', verbose_name='Населённый пункт')),
            ],
            options={
                'verbose_name': 'Тип подключения',
                'verbose_name_plural': 'Типы подключений',
            },
        ),
    ]
