# Generated by Django 4.2.16 on 2024-12-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Общая сумма оплаты за заказ', max_digits=10, verbose_name='Общая сумма оплаты'),
        ),
    ]
