# Generated by Django 4.2.16 on 2024-12-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
