# Generated by Django 4.2.16 on 2025-01-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_requiredpayment'),
        ('orders', '0003_rename_fist_name_order_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='initial_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='registration_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='registration_fee_initial_payment',
            field=models.ForeignKey(blank=True, help_text='Платёж за регистрацию и минимальный платёж', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.requiredpayment', verbose_name='Платёж за регистрацию и минимальный платёж'),
        ),
    ]
