# Generated by Django 4.2.16 on 2025-01-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_initial_payment_order_registration_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='initial_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='registration_fee',
        ),
    ]
