# Generated by Django 4.2.16 on 2025-01-02 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_initial_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
